task_name: gaussian_deblur
task_config:
  operator_config:
      name: gaussian_blur
      kernel_size: 61
      intensity: 3.0
      sigma: 0.05

pixel:
  sampler_config:  
    n_restarts: 100
    n_ode_steps: 10
    
    lr: 2e-2
    lam: 0.75
    num_iters: 10
    sigma_restart: 50 

ldm:
  sampler_config:  
    n_restarts: 50
    n_ode_steps: 5
    
    lr: 0.08
    lam: 0.001
    num_iters: 10
    # sigma_restart: 50 # 10 #41.64



    
