task_name: phase_retrieval
task_config:
  operator_config:
    name: phase_retrieval
    oversample: 2.0
    sigma: 0.05

pixel:
  sampler_config:  
    n_restarts: 400
    n_ode_steps: 10
    
    lr: 5e-3
    lam: 0.6
    num_iters: 20 #40
    sigma_restart: 10 
    # rho: 14.38

ldm:
  sampler_config:  
    n_restarts: 100
    n_ode_steps: 10
    
    lr: 0.03
    lam: 0.002
    num_iters: 10
    # sigma_restart: 10 
